# Generated by Django 5.0.1 on 2024-02-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True, verbose_name='사용자 이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=28, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=10, unique=True, verbose_name='닉네임')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('social_media_accounts', models.JSONField(blank=True, default=dict, null=True, verbose_name='소셜 미디어 계정')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='프로필 사진')),
            ],
        ),
    ]
