# Generated by Django 5.0.1 on 2024-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, verbose_name='사용자 아이디'),
        ),
    ]
