# Generated by Django 5.0.1 on 2024-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('password_confirm', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
